# Generated by Django 4.1.7 on 2023-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='darba_nosaukums')),
                ('work_date', models.DateField(verbose_name='darba diena')),
                ('work_time1', models.TimeField(verbose_name='darba sākuma laiks')),
                ('work_time2', models.TimeField(verbose_name='darba beigas laiks')),
            ],
        ),
    ]
